### ISSUE TITLE
Chrome is not loading the website to debug

### ISSUE THREAD

**Issue by JanFellner** [mpotthoff/vscode-android-webview-debug#12]
Hi,

i am now playing around and try to get this plugin working but i have setup issues.
First: All the prerequisites are done. I see the device in chrome://inspect/#devices. I can launch the plugin. If i have a debugger statement present vscode is showing the javascript for it.

But:
* I am failing to get the website displayed on the mobile with F5. If i manually open it using chrome://inspect/#devices the debugger statement lands in vscode. Sadly #1 did not mentino how he solved it. On my side it´s a classic start-react-app project using typescript and webpacked javascript. Launching the Plugin simply shows no change on the mobile. It just stays the same as if i just opened chrome.
 
* VSCode is complaining about the webRoot Attribute in the launch config. How do i specify the properl url the android chrome application should load. 
![grafik](https://user-images.githubusercontent.com/53753460/180995065-0c9a12a4-693f-462d-b1cf-d42127ba003f.png)

Thanks in advance,

Jan

**Comment by mpotthoff** [comment]
Hey Jan,

this extension only allows the `attach`-type configuration of the `vscode-js-debug` extension (https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md#pwa-chrome-attach). So we only allow attaching to an already running application that has the sourcecode already loaded in some way.
What you want is the `launch` type that is used on desktops to directly start chrome with a specific website. We don't support this because the extension is mainly meant for debugging embedded webviews inside applications and it's not possible to automatically deploy and launch any code in a generic way. For this reason it's the responsibility of any project using this extension to deploy the sourcecode itself and the start the application using e.g. the `preLaunchTask`.

Regarding the `webRoot` parameter:
The warning can be ignored. We don't have it specified in our `package.json`, but we will stay pass any parameters along to `vscode-js-debug`. But just fyi the `webRoot` parameter does not specify the launch url, but the location where the debugger can find the served files on your local system. The launch url can be configured using the `url` parameter but this is not supported in the `attach`-type configuration.
