### ISSUE TITLE
VS Code always says 'no devices found'

### ISSUE THREAD

**Issue by halindrome** [mpotthoff/vscode-android-webview-debug#13]
I am using version 1.2.2 in VS Code version 1.87.2 on MacOS 13.6.4.

Previously I could attach to a webview on an android device that was connected to this machine.  Even an older device (e.g., Android 9) worked well.

Now whenever I attempt to connect it always reports "No devices found".  However, opening chrome://inspect on the same machine shows devices and I am able to connect and debug using the Chrome DevTools.  Also, `adb devices` from the command line shows the connected device.

I am at a loss.  And I really miss having this work correctly.

**Comment by mpotthoff** [comment]
@halindrome 

Hmh. For me the extension still works fine. The message `No devices found` indicates that it didn't find any devices with adb.

Could you execute `adb devices -l` on your command line and paste the output here?
Also did you configure `android-webview-debug.adbPath` or is that still on its default value?
You could also try unchecking `Discover USB devices` on `chrome://inspect`. Otherwise Chrome will start its own instance of ADB and basically "steal" any connected devices so that they won't be visible for the normal ADB instance on the command line.

**Comment by halindrome** [comment]
`adb devices -l` reports this:

`List of devices attached
3082MH1001068280       device 20-1.1.1 product:Armor_X5 model:Armor_X5 device:Armor_X5 transport_id:2`

This happens from a regular terminal window, and also from within the embedded terminal in VSCode (just in case there was some different PATH in play).

adbPath is set to the default `adb`

I have unchecked this.  I have also tried just closing chrome altogether.

**Comment by mpotthoff** [comment]
@halindrome 

So the problem should be resolved with the latest version 1.2.3. The output of `adb devices -l` seems to be a bit different when libusb is used under the hood by ADB. Please let me know if this resolves your issue :)

**Comment by Omikorin** [comment]
@mpotthoff I can say this fix resolved the issue on Ubuntu 22.04 :) Thank you!

**Comment by halindrome** [comment]
Also on MacOS.  Thanks so much for the quick response!
