### ISSUE TITLE
"cat: /proc/net/unix: Permission denied" after selecting device

### ISSUE THREAD

**Issue by patriksh** [mpotthoff/vscode-android-webview-debug#4]
I get the following error `cat: /proc/net/unix: Permission denied"` after selecting my device.

**Comment by mpotthoff** [comment]
I have't seen that error before on any device that I tested with. Do you have some more information for me? Like what kind of device are you working with, Android version etc.?

**Comment by patriksh** [comment]
OS: Pop!_OS 21.04

Phone: Xiaomi Poco X3 with Android 11

Debugging works fine in `chrome://inspect`.

**Comment by mpotthoff** [comment]
Huh that's interesting because chrome uses the exact same way to discover the available sockets.
What happens when you run `adb shell "cat /proc/net/unix"` manually in your terminal?

**Comment by patriksh** [comment]
Permission denied again. I wrote wrong about Chrome, the device is listed on inspect list, but actually I don't get the "Inspect" button.

**Comment by mpotthoff** [comment]
I'm sorry to say this but I think you are out of luck then 😕 We need access to `/proc/net/unix` to find the possible debugging targets but if even chrome itself has no way around that then we also have no chance. Probably Xiaomi has changed something in their system image (for whatever reason) which causes this.

**Comment by patriksh** [comment]
Perhaps could be the fact that I have a custom ROM?

I'll try with a Samsung with stock ROM.

**Comment by mpotthoff** [comment]
I'm going to close this issue because the problem is not caused by the extension but seems to be a problem with this specific ROM.

**Comment by acognigni-evotecnia** [comment]
Sorry for bumping this.

I'm also on a custom ROM (and root access and had this same issue. for now, I've fixed by giving global read access to /proc/net/unix it like this:

WARNING: I'm not sure how safe this is. It probably wont break your phone, but it could enable some exploit that could be used by a visrus. we will be messing with your phone permissions and takeing to to undoit once we are done.

1. connect phone to pc and allow / authorize USB Debugging
2. open a new windows terminal / powershell and type `adb shell`
3. once you have an android shell run the command `su`
4. on your phone you will see a prompt asking if you want to allow root over USB debug, Say yes
5. the run `ls -la /proc/net/unix` and TAKE NOTE OF THE OUTPUT. 
        It's important to take note of the output sin it's showing you the permissions it had before we messed with it. mine was
        `-r--r----- 1 root root 0 2022-08-08 10:38 /proc/net/unix`
        the 8th character (in this case a -) indicates that that file is not public for reading
6. now run  `chmod o+r /proc/net/unix`. this command says that you want change / modify a file by giving "others" (others is everyone that is not the android system) the permission to read
7. run  `ls -la /proc/net/unix` once again. this time it will show an 'r' on the 8th position
        mine says `-r--r--r-- 1 root root 0 2022-08-08 10:39 /proc/net/unix`
8. once you are done run  `chmod o-r /proc/net/unix`. to undo it
